# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Inke_Swift3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Inke_Swift3
pod 'Just'
pod 'Kingfisher'
pod 'MJRefresh'

end
